# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ManyToManyField(related_name='course_id', to='core.Course'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_members',
            field=models.ManyToManyField(related_name='members', to='core.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ManyToManyField(related_name='po', to='core.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_first',
            field=models.CharField(default='', max_length=20),
        ),
    ]
