# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170211_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
