# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_course_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.CharField(default='collab', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(default="It's alsways Spring", max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
