# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170212_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ManyToManyField(related_name='po', to='core.User'),
        ),
    ]
