# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.RemoveField(
            model_name='project',
            name='current_members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='No Project Title Provided', max_length=255),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
