# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170213_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
