# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project2_members'),
        ('core', '0008_delete_project'),
    ]

    operations = [
    ]
