# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('name', models.TextField(blank=True, max_length=75)),
                ('institution', models.TextField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('avatar', models.ImageField(default='', upload_to='avatars/')),
                ('isProf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('skill',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='known_skills',
            field=models.ManyToManyField(default='', related_name='known', to='profiles.Skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='learn_skills',
            field=models.ManyToManyField(default='', related_name='learn', to='profiles.Skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
