# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='known_skills',
            field=models.ManyToManyField(to='profiles.Skills'),
        ),
    ]
