# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_profile',
        ),
    ]
