# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20170928_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('client_id', models.TextField(default='')),
                ('client_secret', models.TextField(default='')),
                ('scopes', models.TextField(default='')),
                ('invalid', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
