# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170928_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Tech',
                'verbose_name_plural': 'Techs',
                'ordering': ('tech',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='known_techs',
            field=models.ManyToManyField(default='', related_name='known', to='profiles.Techs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='learn_techs',
            field=models.ManyToManyField(default='', related_name='learn', to='profiles.Techs'),
        ),
    ]
