# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190227_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.TextField(default='skin-green-light', max_length=25),
        ),
    ]
