# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170227_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ('skill',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
