# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'ordering': ('user',), 'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AddField(
            model_name='profile',
            name='meeting_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
