# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170306_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_folder/Default/goonies.jpg', upload_to='avatar_folder/'),
        ),
    ]
