# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170227_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='known_skills',
            field=models.ManyToManyField(default='', related_name='known', to='profiles.Skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learn_skills',
            field=models.ManyToManyField(default='', related_name='learn', to='profiles.Skills'),
        ),
    ]
