# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_isprof'),
        ('profiles', '0006_auto_20170227_2352'),
    ]

    operations = [
    ]
