# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_merge_20170301_0023'),
        ('profiles', '0007_merge_20170228_1656'),
    ]

    operations = [
    ]
