# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20171027_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
