# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20171103_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
