# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20171103_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hasProject',
            field=models.BooleanField(default=False),
        ),
    ]
