# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20171127_2120'),
        ('chat', '0010_auto_20171127_2122'),
    ]

    operations = [
    ]
