# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(default='No Creator (Weird)', max_length=255),
        ),
    ]
