# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='projects',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='users',
            new_name='user',
        ),
    ]
