# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tsr_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsr',
            name='slug',
            field=models.CharField(default='', max_length=20, unique=False),
        ),
    ]
