# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avail_mem',
            field=models.BooleanField(default=True),
        ),
    ]
