# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_avail_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
