# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tsr_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsr',
            name='slug',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
