# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171019_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='scrum_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resourceupdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
