# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desired_skills',
            field=models.ManyToManyField(default='', related_name='desired', to='profiles.Skills'),
        ),
    ]
