# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interest',
            field=models.ManyToManyField(default='', to='projects.Interest'),
        ),
    ]
