# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_technologies'),
        ('projects', '0004_auto_20171019_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desired_technologies',
            field=models.ManyToManyField(default='', related_name='desired', to='profiles.Technologies'),
        ),
    ]
