# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20171019_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsr_number', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('analysis_type', models.CharField(default='', max_length=255)),
                ('analysis_output', models.CharField(default='', max_length=255)),
                ('flag_tripped', models.BooleanField(default=False)),
                ('flag_detail', models.CharField(default='', max_length=255)),
                ('associated_member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='associated_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='analysis',
            field=models.ManyToManyField(default=None, related_name='project_analysis', to='projects.Analysis'),
        ),
    ]
