# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171019_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
