# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='swag', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
