# -*- coding: utf-8 -*-
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 1.11.18 on 2019-02-21 00:16
=======
# Generated by Django 1.11.18 on 2019-02-20 02:55
>>>>>>> 7e7f500... Merge pull request #2 from Hnguyen1997/Nikki
=======

# Generated by Django 1.11.18 on 2019-02-21 00:16
=======
# Generated by Django 1.11.18 on 2019-02-20 02:55

>>>>>>> 9f4e50f... Merge branch 'master' into Anisha
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('profiles', '0003_auto_20190221_0016'),
=======
        ('profiles', '0003_auto_20190220_0255'),
>>>>>>> 7e7f500... Merge pull request #2 from Hnguyen1997/Nikki
=======

        ('profiles', '0003_auto_20190221_0016'),

>>>>>>> 9f4e50f... Merge branch 'master' into Anisha
        ('projects', '0005_auto_20190130_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desired_techs',
            field=models.ManyToManyField(default='', related_name='technologies', to='profiles.Techs'),
        ),
    ]
