# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_desired_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_reason',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
