# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190118_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceupdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
