# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='Default Content', max_length=4000),
            preserve_default=False,
        ),
    ]
