# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171104_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='flag_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='tsr_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
