# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171104_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='flag_tripped',
        ),
    ]
