# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resource',
            field=models.TextField(default='This is a resource default', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update',
            field=models.TextField(default='Update Default', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update_title',
            field=models.CharField(default='Update Title Default', max_length=255),
            preserve_default=False,
        ),
    ]
