# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190228_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desired_techs',
            field=models.ManyToManyField(default='', related_name='technologies', to='projects.Techs'),
        ),
    ]
