# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190125_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_request',
            field=models.BooleanField(default=False),
        ),
    ]
