# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_analysis_flag_tripped'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='flag_suppress',
            field=models.BooleanField(default=False),
        ),
    ]
