# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_no_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scrum_master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
