# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190125_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scrum_master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrum_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='ta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to=settings.AUTH_USER_MODEL),
        ),
    ]
