# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170303_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ('-date',), 'verbose_name': 'Project Update', 'verbose_name_plural': 'Project Updates'},
        ),
    ]
