# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='limit_creation',
        ),
    ]
