# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170306_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.CharField(default='Fefault', max_length=255),
        ),
    ]
