# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170928_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.CharField(default='There is no Course Description', max_length=400),
        ),
    ]
