# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170929_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.CharField(default='There is no Course Description', max_length=300),
        ),
    ]
