# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170305_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='limit_creation',
            field=models.BooleanField(default=False),
        ),
    ]
