# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tsr_late'),
        ('courses', '0003_auto_20170929_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subs',
            field=models.ManyToManyField(default='', related_name='ass', to='projects.Tsr'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(related_name='course', to='courses.Assignment'),
        ),
    ]
