# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170929_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
