# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20170307_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title Provided', max_length=255)),
                ('content', models.TextField(default='*No Content Provided*', max_length=2000)),
                ('date_post', models.DateTimeField()),
                ('date_edit', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Course Update',
                'verbose_name_plural': 'Course Updates',
                'ordering': ('-date_post', '-date_edit', 'title'),
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
