# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171018_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(default=2018, max_length=20),
        ),
    ]
