# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170222_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='addCode',
        ),
    ]
