# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180109_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(default=2019, max_length=20),
        ),
    ]
