# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_addcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='addCode',
            field=models.CharField(default='AAAAAAAA', max_length=8),
        ),
    ]
