# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180109_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reason1',
            field=models.TextField(default='', max_length=38),
        ),
    ]
