# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_reason1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.TextField(default='', max_length=38)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='reason1',
        ),
    ]
