# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190115_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
