# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190123_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
