# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-12 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='receivers',
            field=models.TextField(default='None'),
        ),
    ]
