# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170222_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.CharField(default='There is no Course Description', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
