# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170227_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(default='No Term Selected', max_length=20),
        ),
    ]
