# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_sponsor'),
        ('courses', '0015_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
